version: '3'

services:
  php:
    build: .
    volumes:
      - ./:/workdir
    depends_on:
      - mysql
    tty: true

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
